### ISSUE TITLE
Underlying card appears not smootly

### ISSUE THREAD

**Issue by robertBadamshin** [yuyakaido/CardStackView#276] opened 2019-08-31 06:58 UTC

**Comment by yuyakaido** [comment] 2019-10-06 14:44
@robertBadamshin 
There had been a performance problem caused by a needless onBindViewHolder invocation in less than or equal to ver. 2.2.3. This issue had been fixed in [ver. 2.2.4](https://github.com/yuyakaido/CardStackView/releases/tag/v2.2.4).

**Closed by yuyakaido** 2019-10-06 14:44 UTC
