### ISSUE TITLE
Card flash

### ISSUE THREAD

**Issue by hockleongloh** [yuyakaido/CardStackView#197] opened 2019-02-27 10:36 UTC
When i started to swipe or drag the card, it will keep on blink and flashing

Hope to get your reply ASAP.
Thanks.

Library version : 2.2.3

**Comment by hari2109** [comment] 2019-03-13 10:48
What type of layout do you have within your card item? If there's any layout which is dynamically populated, that might be the issue.

**Comment by yuyakaido** [comment] 2019-03-16 17:01
@hockleongloh @hari2109 
I can't reproduce this issue. But maybe this issue has been fixed in [ver. 2.2.4](https://github.com/yuyakaido/CardStackView/releases/tag/v2.2.4). There is a problem that Adapter.onBindViewHolder is invoked while dragging before ver. 2.2.4.

**Closed by yuyakaido** 2019-03-16 17:01 UTC
