### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by bhavesh350** [yuyakaido/CardStackView#154] opened 2018-12-05 09:23 UTC
java.lang.NullPointerException
	at com.yuyakaido.android.cardstackview.CardStackView.onTouch(CardStackView.java:48)
	at android.view.View.dispatchTouchEvent(View.java:7709)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2212)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1945)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2135)
	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1582)
	at android.app.Activity.dispatchTouchEvent(Activity.java:2469)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2083)
	at android.view.View.dispatchPointerEvent(View.java:7894)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4010)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3886)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3447)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3497)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3466)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3573)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3474)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3630)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3447)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3497)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3466)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3474)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3447)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5595)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5575)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5546)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5675)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:138)
	at android.os.Looper.loop(Looper.java:123)
	at android.app.ActivityThread.main(ActivityThread.java:5113)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by yuyakaido** [comment] 2018-12-09 10:18
@bhavesh350 
I can't reproduce this issue.
Can you send a sample project to fix this issue?

**Comment by yuyakaido** [comment] 2018-12-21 16:42
@bhavesh350 
This issue has been fixed in [2.2.1](https://github.com/yuyakaido/CardStackView/releases/tag/v2.2.1).

**Closed by yuyakaido** 2018-12-21 16:42 UTC
