### ISSUE TITLE
When facebook native ads placed inside cardstackview , ads are getting hidden .

### ISSUE THREAD

**Issue by kdblue** [yuyakaido/CardStackView#199] opened 2019-03-11 17:05 UTC
See this error, how can I solve this?

https://stackoverflow.com/questions/55106680/how-to-place-facebook-native-ads-in-cardstackview-native-ads-gets-hidden-when-a

**Comment by kolllor33** [comment] 2019-03-15 23:18
I think this bug has nothing to do with the library. The problem is that recycleviews are strangs with video and the ads and the library is based on a recycleview it wil have this bug. So I don't know if you find https://stackoverflow.com/questions/33908308/facebook-native-ads-in-recycler-view-android this somthing helpfull?

**Comment by kdblue** [comment] 2019-03-16 14:11
@kolllor33 thanks for your response, I found the issue in this library which makes ads hidden on dragging, finally I fixed it, now I am trying to play video ads in this library once I did with this issue I will merge into the main code.

Thanks, @yuyakaido and other developers for this library😃

**Comment by yuyakaido** [comment] 2019-03-16 17:00
@kdblue @kolllor33 
I can't reproduce this issue. But maybe this issue has been fixed in [ver. 2.2.4](https://github.com/yuyakaido/CardStackView/releases/tag/v2.2.4). There is a problem that `Adapter.onBindViewHolder` is invoked while dragging before ver. 2.2.4.

**Closed by yuyakaido** 2019-03-16 17:00 UTC

**Comment by kdblue** [comment] 2019-03-16 19:12
I tried ver 2.2.4 is buggy while moving previously cards.
