### ISSUE TITLE
PlayerView flashes

### ISSUE THREAD

**Issue by moogii** [yuyakaido/CardStackView#174] opened 2018-12-23 09:30 UTC
On version 2.0.0, there wasn't any issue.
After 2.0.1, Exoplayer's PlayerView flashes when swiping.
![1](https://user-images.githubusercontent.com/5917577/50382258-3d234380-06d6-11e9-8835-1aea172e7d9b.jpg)
![2](https://user-images.githubusercontent.com/5917577/50382257-3d234380-06d6-11e9-9eb0-08fc4d0c89f6.jpg)

Also, can you add transparent overlay like image shown below. When swiping decrease the alpha of overlay same as increasing alpha of right, left, top and bottom overlay.
![3](https://user-images.githubusercontent.com/5917577/50382320-a22b6900-06d7-11e9-8976-8661a0674b06.jpg)

Thank you

**Comment by hockleongloh** [comment] 2019-02-27 11:46
@yuyakaido Can try to figure out this issue?

**Comment by yuyakaido** [comment] 2019-03-16 17:05
@moogii @hockleongloh 
I can't reproduce this issue. But maybe this issue has been fixed in [ver. 2.2.4](https://github.com/yuyakaido/CardStackView/releases/tag/v2.2.4). There is a problem that Adapter.onBindViewHolder is invoked while dragging before ver. 2.2.4.

**Closed by yuyakaido** 2019-03-16 17:05 UTC
