### ISSUE TITLE
First frame of rewind animation shows final animated state

### ISSUE THREAD

**Issue by damien5314** [yuyakaido/CardStackView#251] opened 2019-05-14 18:10 UTC
Hi, I'm observing a small UI glitch while trying out the `CardStackView.rewind()` API. It seems after calling `rewind()`, the previous card (i.e. the card that is about to be rewound into view) is shown where the current card is, before animation takes place to move the previous card on top of the current card. 

It's best seen by checking a video in action: https://drive.google.com/file/d/1GQ7iPd0zrH36jJbOAHA_kEvlUydGKHq_/view?usp=sharing

| frame 0 | frame 1 | frame 2 | frame 3 | frame 4 |
|---|---|---|---|---|
|![Screenshot 2019-05-14 11 04 04](https://user-images.githubusercontent.com/1700953/57721152-53f01580-7638-11e9-9bd3-6d7cdbdc30e0.png) |![Screenshot 2019-05-14 11 04 11](https://user-images.githubusercontent.com/1700953/57721158-58b4c980-7638-11e9-9956-2043b9162ae0.png) |![Screenshot 2019-05-14 11 04 16](https://user-images.githubusercontent.com/1700953/57721167-5fdbd780-7638-11e9-9097-983a81223744.png) |![Screenshot 2019-05-14 11 04 20](https://user-images.githubusercontent.com/1700953/57721185-68cca900-7638-11e9-8907-9496d496a28a.png) | ![Screenshot 2019-05-14 11 04 23](https://user-images.githubusercontent.com/1700953/57721197-72561100-7638-11e9-901d-c5be0c03066a.png)|

Is the animator pushing the card into its final resting position on the first frame of the animation, then moving it down to its proper place? It's hard for me to tell 😓 Any help would be appreciated 🙇

**Comment by yueban** [comment] 2019-05-23 06:42
I've got the same problem and try to solve it for a while. Here's what I found:

**1. how does the problem happen?**

you can find this part of code in `CardStackSmoothScroller`:
```
if (type == ScrollType.AutomaticRewind) {
    manager.getCardStackState().scrollerStatus = CardStackState.ScrollerStatus.onSeekTargetStep;

    manager.removeAllViews();
    RewindAnimationSetting setting = manager.getCardStackSetting().rewindAnimationSetting;
    action.update(
            -getDx(setting),
            -getDy(setting),
            setting.getDuration(),
            setting.getInterpolator()
    );
```

it will remove all views and then use the scroller to start a scroll event. The scroll event make dx/dy changed and invoke `scrollHorizontallyBy/scrollVerticallyBy` function. Finally it jump into `CardStackLayoutManager.update` function and update child views.

the problem is, when `it remove all views`, the dx/dy is 0, so you see the topView at the original position on first frame. the it animate correctly cause the scroll event has began.

**2. how to solve it?**

I found a way to determine if it is the first frame of rewind animation which is the moment `all view removed` as we mentioned above.

you can check the implementation on the [commit](https://github.com/yueban/CardStackView/commit/415aec4b67a5138ecf0f0ab62f3887d8fb6432be).

**Comment by yuyakaido** [comment] 2019-06-07 14:38
@damien5314 @yueban 
Thank you for your report!
This issue has been fixed in [ver. 2.3.4](https://github.com/yuyakaido/CardStackView/releases/tag/v2.3.4).

**Closed by yuyakaido** 2019-06-07 14:38 UTC

**Comment by damien5314** [comment] 2019-06-10 18:04
@yuyakaido Works wonderfully, thank you!
