### ISSUE TITLE
flickering/blinking effect will occur when give cardStackLayoutManager.setMaxDegree(20.0f);

### ISSUE THREAD

**Issue by ilaxopavan** [yuyakaido/CardStackView#268] opened 2019-07-16 10:55 UTC
if i provide max degree to 20.0f data inside cardview is blink rapidly in center when dragging from left or right,

works properly if provide maxdegree to 0.0f,

please check this issue,otherwise your library was awesome.

**Comment by yuyakaido** [comment] 2019-10-06 13:50
@ilaxopavan 
There had been a flickering/blinking problem caused by a needless onBindViewHolder invocation in less than or equal to ver. 2.2.3. This issue had been fixed in [ver. 2.2.4](https://github.com/yuyakaido/CardStackView/releases/tag/v2.2.4).

**Closed by yuyakaido** 2019-10-06 13:50 UTC

**Comment by yuyakaido** [comment] 2019-10-06 13:55
@ilaxopavan 
You can get more information about the issue in this [issue](https://github.com/yuyakaido/CardStackView/issues/176).
